/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example:
s = "abcd"
t = "abcde"

Step-by-step XOR:

a ^ b ^ c ^ d ^ a ^ b ^ c ^ d ^ e
→ (a^a) ^ (b^b) ^ (c^c) ^ (d^d) ^ e
→ 0 ^ 0 ^ 0 ^ 0 ^ e
→ e

✅ Output: 'e'
*/
package string;
class Solution {
    public char findTheDifference(String s, String t) {
        char result = 0;

        // XOR all characters of s
        for (char c : s.toCharArray()) {
            result ^= c;
        }

        // XOR all characters of t
        for (char c : t.toCharArray()) {
            result ^= c;
        }

        return result;
    }
}